# we don't use it, but we also do not want default (ruby) image
language: go

services:
  - docker

# skip default (go get -t -v ./... install step
install: true

script:
  - docker build
      --build-arg CODECOV_TOKEN=$CODECOV_TOKEN
      --build-arg CI=$CI
      --build-arg TRAVIS=$TRAVIS
      --build-arg TRAVIS_BRANCH=$TRAVIS_BRANCH
      --build-arg TRAVIS_COMMIT=$TRAVIS_COMMIT
      --build-arg TRAVIS_JOB_ID=$TRAVIS_JOB_ID
      --build-arg TRAVIS_JOB_NUMBER=$TRAVIS_JOB_NUMBER
      --build-arg TRAVIS_OS_NAME=$TRAVIS_OS_NAME
      --build-arg TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST
      --build-arg TRAVIS_PULL_REQUEST_SHA=$TRAVIS_PULL_REQUEST_SHA
      --build-arg TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG
      --build-arg TRAVIS_TAG=$TRAVIS_TAG
      .

addons:
  code_climate:
    repo_token: b3b137f48bcd4e7fc58959706e292888be90f06c51822f6105fe50c0e1502191

jobs:
  include:
    - dist: trusty
      name: Integration Tests
    - os: windows
      go: "1.9.x"
      script:
        - go get -t -v -tags "sqlite integration_test" ./...
        - go test -v -tags "sqlite integration_test" -race ./...
    - os: windows
      go: "1.10.x"
      script:
        - go get -t -v -tags "sqlite integration_test" ./...
        - go test -v -tags "sqlite integration_test" -race ./...
    - os: windows
      go: "1.11.x"
      env:
        - GO111MODULE=off
      script:
        - go get -t -v -tags "sqlite integration_test" ./...
        - go test -v -tags "sqlite integration_test" -race ./...
    - os: windows
      go: "1.11.x"
      env:
        - GO111MODULE=on
      script:
        - go get -t -v -tags "sqlite integration_test" ./...
        - go test -tags "sqlite integration_test" -race ./...
    - os: linux
      go: "1.9.x"
      script:
        - go get -t -v -tags "sqlite integration_test" ./...
        - go test -v -tags "sqlite integration_test" -race ./...
    - os: linux
      go: "1.10.x"
      script:
        - go get -t -v -tags "sqlite integration_test" ./...
        - go test -v -tags "sqlite integration_test" -race ./...
    - os: linux
      go: "1.11.x"
      env:
        - GO111MODULE=off
      script:
        - go get -t -v -tags "sqlite integration_test" ./...
        - go test -v -tags "sqlite integration_test" -race ./...
    - os: linux
      go: "1.11.x"
      env:
        - GO111MODULE=on
      script:
        - go get -t -v -tags "sqlite integration_test" ./...
        - go test -v -tags "sqlite integration_test" -race ./...
