sudo: required

services:
  - docker
install: false

go:
  - 1.7

env:
  matrix:
    - GO_DOCKER_TAG=1.7
    - GO_DOCKER_TAG=1.8

script:
  - perl -pi -w -e "s/FROM golang:1.7/FROM golang:$GO_DOCKER_TAG/g" Dockerfile && docker build .

addons:
  code_climate:
    repo_token: b3b137f48bcd4e7fc58959706e292888be90f06c51822f6105fe50c0e1502191
