name: Tests
on: [push, pull_request]
jobs:
  tests-off:
    name: ${{ matrix.go-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        os: [macos-latest, windows-latest, ubuntu-latest]
    env:
      GO111MODULE: on
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: src/github.com/${{ github.repository }}
        submodules: 'recursive'
    - name: Test
      run: |
        go mod tidy -v
        go test -tags "sqlite" -cover  ./...
